{% set name = "vastdb" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vastdb-{{ version }}.tar.gz
  sha256: 00b1af0148a5daea0de6dd1a80b511f6213ec4eedb2be38f15fa1d21fd8a1d16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - aws-requests-auth
    - backoff 2.2.1
    - boto3
    - python-flatbuffers
    - ibis-framework 9.0.0
    - ibis-framework-core 9.0.0
    - pyarrow
    - requests
    - xmltodict

test:
  imports:
    - vast_flatbuf
    - vastdb
  commands:
    - pip check
  requires:
    - pip
    - pyarrow <16

about:
  home: https://github.com/vast-data/vastdb_sdk
  summary: VAST Data SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
