{% set name = "vastdb" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vastdb-{{ version }}.tar.gz
  sha256: 8848f3c92b87517fca0b58a8856dec0a73fa23d9586d877e276c255a67b32622

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - aws-requests-auth
    - backoff 2.2.1
    - boto3
    - python-flatbuffers
    - ibis-framework 8.0.0
    - pyarrow
    - requests
    - xmltodict

test:
  imports:
    - vast_flatbuf
    - vastdb
  commands:
    - pip check
  requires:
    - pip
    - pyarrow <16

about:
  home: https://github.com/vast-data/vastdb_sdk
  summary: VAST Data SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
