{% set name = "vastdb" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vastdb-{{ version }}.tar.gz
  sha256: a1a795629e081a3f6b3bb648c9e9991150aed7ecf7e36d6b459196acc72d1608

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - aws-requests-auth
    - boto3
    - python-flatbuffers
    - ibis-framework
    - pyarrow
    - requests
    - xmltodict

test:
  imports:
    - vast_flatbuf
    - vastdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vast-data/vastdb_sdk
  summary: VAST Data SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
